server:
  port: 9003
spring:
  application:
    name: tensquare-qa #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.22.128:3306/tensquare_qa?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
