server:
  port: 9002
spring:
  application:
    name: tensquare-recruit #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/tensquare_recruit?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
