server:
  port: 9001
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.22.128:3306/tensquare_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
